name: Check Download URL

on:
  release:
    types:
      - created

jobs:
  check_url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release
      id: get_release
      run: |
        releases=$(curl -s "https://api.github.com/repos/latisinspur/latisinspur.github.io/releases")
        latest_tag=$(echo "$releases" | jq -r '.[0].tag_name')
        echo "::set-output name=tag::$latest_tag"
      
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.qq.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: 846162223@qq.com
        to: me@lhxone.com,liuhaoxin@inspur.com
        subject: LATIS iOS New Version
        body: |
          Dear LATIS Maintainers:
          
          The Latis iOS App released a new version.
          URL: https://github.com/latisinspur/latisinspur.github.io/releases
          Latest Release Tag: ${{ steps.get_release.outputs.tag }}
          
          
          From GitHub Action

