name: Check Download URL

on:
  release:
    types:
      - created

jobs:
  check_url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release
      id: get_release
      run: |
        releases=$(curl -s "https://api.github.com/repos/latisinspur/latisinspur.github.io/releases")
        latest_tag=$(echo "$releases" | jq -r '.[0].tag_name')
        echo "::set-output name=tag::$latest_tag"
        
    - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: 846162223@qq.com <846162223@qq.com>
          to: me@lhxone.com
          subject: Hello from GitHub Actions
          body: |
            This is the email body.
            It can have multiple lines.
    
